# Generated by Django 4.0.4 on 2024-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento_workshop',
            name='fecha_workshop',
            field=models.DateField(),
        ),
    ]
