# Generated by Django 4.0.4 on 2024-08-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('distrito', models.CharField(max_length=200)),
                ('slug', models.CharField(default='', max_length=200)),
                ('fecha_entrega', models.DateField(blank=True)),
                ('fecha_ingreso', models.DateField(default='1900-02-01')),
                ('nombre_real', models.CharField(default='', max_length=200)),
                ('inmobiliaria', models.CharField(default='', max_length=200)),
                ('persona_contacto_1', models.CharField(default='', max_length=200)),
                ('correo_1', models.CharField(default='', max_length=200)),
                ('crm', models.CharField(default='', max_length=200)),
                ('tipo_envio_leads', models.CharField(choices=[('crm', 'Crm'), ('correo', 'Correo'), ('whatsapp', 'Whatsapp')], default='crm', max_length=20)),
                ('link_brochure', models.CharField(default='', max_length=500)),
                ('etapa', models.CharField(choices=[('planos', 'Planos'), ('preventa', 'Preventa'), ('construccion', 'Construccion'), ('entrega inmediata', 'Entrega Inmediata')], default='planos', max_length=20)),
                ('banco', models.CharField(choices=[('bbva', 'Bbva'), ('banbif', 'Banbif'), ('scotiabank', 'Scotiabank'), ('ibk', 'Ibk'), ('bcp', 'Bcp'), ('todos', 'Todos')], default='todos', max_length=20)),
                ('tipo_moneda', models.CharField(choices=[('pen', 'Soles'), ('usd', 'Dolar')], default='pen', max_length=20)),
                ('nro_pisos', models.IntegerField(default=0)),
                ('nro_dptos', models.IntegerField(default=0)),
                ('valor_de_separacion', models.FloatField(default=0)),
                ('valor_porcentaje_inicial', models.FloatField(default=0)),
                ('valor_porcentaje_financiado', models.FloatField(default=0)),
                ('areas_comunes', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('coworking', models.BooleanField(default=False)),
                ('cine', models.BooleanField(default=False)),
                ('parrilla', models.BooleanField(default=False)),
                ('sum', models.BooleanField(default=False)),
                ('bicicleta', models.BooleanField(default=False)),
                ('workshop', models.BooleanField(default=False)),
                ('web', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('dias_vacancia', models.FloatField(default=0)),
                ('costo_porcentaje_operativo', models.FloatField(default=0)),
                ('costo_porcentaje_administrativo', models.FloatField(default=0)),
                ('costo_porcentaje_instalacion', models.FloatField(default=0)),
                ('corretaje', models.BooleanField(default=False)),
                ('tasa_credito', models.FloatField(default=0.06)),
                ('costo_porcentaje_capex_reparaciones', models.FloatField(default=0)),
                ('plazo_meses', models.IntegerField(default=300)),
                ('descuento_porcentaje_preventa', models.FloatField(default=0)),
                ('costo_porcentaje_administrativos_venta', models.FloatField(default=0)),
                ('coordenada_A', models.FloatField(null=True)),
                ('coordenada_B', models.FloatField(null=True)),
            ],
        ),
    ]
