# Generated by Django 4.0.4 on 2024-07-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_user_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='continuidad_laboral',
            field=models.IntegerField(default=0),
        ),
    ]
