# Generated by Django 4.0.4 on 2024-07-09 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyects', '0001_initial'),
        ('departments', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('asesor', models.CharField(max_length=100)),
                ('correo_asesor', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('proyecto_nombre', models.CharField(max_length=20)),
                ('departamento_nro', models.CharField(max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departamento')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyects.proyecto')),
            ],
        ),
    ]
