# Generated by Django 4.0.4 on 2024-07-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipodoc', models.CharField(max_length=100)),
                ('nrodoc', models.CharField(max_length=10)),
                ('email', models.IntegerField()),
                ('edadrango', models.CharField(max_length=100)),
                ('nrocelular', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
    ]
