# Generated by Django 4.0.4 on 2024-08-08 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento_Alquiler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_depa', models.CharField(blank=True, max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('slug', models.CharField(default='', max_length=200)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(default='1900-02-01')),
                ('edificio', models.CharField(blank=True, max_length=50)),
                ('anio_construccion', models.IntegerField(blank=True, default=2024)),
                ('distrito', models.CharField(blank=True, default='lima', max_length=100)),
                ('tipo_moneda', models.CharField(choices=[('pen', 'Soles'), ('usd', 'Dolar')], default='pen', max_length=20)),
                ('estatus', models.CharField(default='no disponible', max_length=100)),
                ('tipo_inventario', models.CharField(choices=[('proyecto', 'Proyecto'), ('c/inquilino', 'Cinquilino')], default='c/inquilino', max_length=100)),
                ('precio', models.FloatField(blank=True, default=0)),
                ('precio_dolar', models.FloatField(null=True)),
                ('nro_dormitorios', models.IntegerField(blank=True, default=1)),
                ('nro_banos', models.IntegerField(blank=True, default=1)),
                ('valor_alquiler', models.FloatField(blank=True, default=0)),
                ('unit_area', models.FloatField(default=1)),
                ('vista', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], default='interior', max_length=20)),
                ('banco', models.CharField(choices=[('bbva', 'Bbva'), ('banbif', 'Banbif'), ('scotiabank', 'Scotiabank'), ('ibk', 'Ibk'), ('bcp', 'Bcp'), ('todos', 'Todos')], default='todos', max_length=20)),
                ('piso', models.IntegerField(blank=True, default=0)),
                ('valor_porcentaje_inicial', models.FloatField(blank=True, default=0)),
                ('valor_porcentaje_financiado', models.FloatField(blank=True, default=0)),
                ('tipo_departamento', models.CharField(blank=True, default='', max_length=200)),
                ('valor_cuota', models.FloatField(blank=True, default=0)),
                ('roi', models.FloatField(blank=True, default=0)),
                ('tir', models.FloatField(blank=True, default=0)),
                ('renta', models.FloatField(blank=True, default=0)),
                ('etapa', models.CharField(choices=[('planos', 'Planos'), ('preventa', 'Preventa'), ('construccion', 'Construccion'), ('entrega inmediata', 'Entrega Inmediata')], default='entrega inmediata', max_length=20)),
                ('areas_comunes', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('coworking', models.BooleanField(default=False)),
                ('cine', models.BooleanField(default=False)),
                ('parrilla', models.BooleanField(default=False)),
                ('sum', models.BooleanField(default=False)),
                ('bicicleta', models.BooleanField(default=False)),
                ('workshop', models.BooleanField(default=False)),
                ('web', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('descuento_porcentaje_preventa', models.FloatField(default=0)),
                ('coordenada_A', models.FloatField(null=True)),
                ('coordenada_B', models.FloatField(null=True)),
                ('patrimonio_inicial', models.FloatField(default=0)),
                ('patrimonio_anio_5', models.FloatField(default=0)),
                ('patrimonio_anio_10', models.FloatField(default=0)),
                ('patrimonio_anio_20', models.FloatField(default=0)),
                ('patrimonio_anio_30', models.FloatField(default=0)),
            ],
        ),
    ]
