# Generated by Django 4.0.4 on 2024-08-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments_rent', '0002_remove_departamento_alquiler_workshop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento_alquiler',
            name='ocultar',
            field=models.BooleanField(default=False),
        ),
    ]
