# Generated by Django 4.0.4 on 2024-07-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='plaza_meses',
        ),
        migrations.AddField(
            model_name='cliente',
            name='plazo_meses',
            field=models.IntegerField(default=0),
        ),
    ]
