# Generated by Django 4.0.4 on 2024-08-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_vacancia', models.FloatField(default=0)),
                ('costo_porcentaje_operativo', models.FloatField(default=0)),
                ('costo_porcentaje_administrativo', models.FloatField(default=0)),
                ('costo_porcentaje_instalacion', models.FloatField(default=0)),
                ('corretaje', models.BooleanField(default=False)),
                ('tasa_credito', models.FloatField(default=0.06)),
                ('costo_porcentaje_capex_reparaciones', models.FloatField(default=0)),
                ('plazo_meses', models.IntegerField(default=300)),
                ('costo_porcentaje_administrativos_venta', models.FloatField(default=0)),
            ],
        ),
    ]
