name: Continous Deployment

on:
  workflow_dispatch:
    inputs:
      choice:
        description: Choose Operation
        options:
          - update
          - deploy
        type: choice

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAQ3EGUNUPNCX7ZI4E

        aws-secret-access-key: 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

        aws-region: us-east-2

    - name: Setup up Requirements
      run: |
        source venv/bin/activate
        chmod +x ./getEnv.sh && ./getEnv.sh
        python load_env.py

    - name: "${{github.event.inputs.choice}}"
      if: github.ref == 'refs/heads/master'
      run: |
            source venv/bin/activate
            zappa "${{github.event.inputs.choice}}" production
    
    - name: "${{github.event.inputs.choice}}"
      if: github.ref == 'refs/heads/develop'
      run: |
            source venv/bin/activate
            zappa "${{github.event.inputs.choice}}" develop        
              